/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OudsButton {
        "accessibleText": string;
        /**
          * @default false
         */
        "coloredBg": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "href"?: string;
        /**
          * @default false
         */
        "iconOnly": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        "loadingTime"?: number;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'strong' | 'brand' | 'minimal' | 'negative';
        /**
          * @default true
         */
        "wrap": boolean;
    }
    interface OudsTextInput {
        "bsPrefix"?: string;
        "bsSuffix"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        "label": string;
        /**
          * @default false
         */
        "maxWidth": boolean;
        /**
          * @default false
         */
        "outlined": boolean;
        /**
          * @default ' '
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        "value"?: string;
    }
}
export interface OudsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOudsButtonElement;
}
declare global {
    interface HTMLOudsButtonElementEventMap {
        "oudsButtonClick": void;
    }
    interface HTMLOudsButtonElement extends Components.OudsButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOudsButtonElementEventMap>(type: K, listener: (this: HTMLOudsButtonElement, ev: OudsButtonCustomEvent<HTMLOudsButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOudsButtonElementEventMap>(type: K, listener: (this: HTMLOudsButtonElement, ev: OudsButtonCustomEvent<HTMLOudsButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOudsButtonElement: {
        prototype: HTMLOudsButtonElement;
        new (): HTMLOudsButtonElement;
    };
    interface HTMLOudsTextInputElement extends Components.OudsTextInput, HTMLStencilElement {
    }
    var HTMLOudsTextInputElement: {
        prototype: HTMLOudsTextInputElement;
        new (): HTMLOudsTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "ouds-button": HTMLOudsButtonElement;
        "ouds-text-input": HTMLOudsTextInputElement;
    }
}
declare namespace LocalJSX {
    interface OudsButton {
        "accessibleText": string;
        /**
          * @default false
         */
        "coloredBg"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "href"?: string;
        /**
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        "loadingTime"?: number;
        "onOudsButtonClick"?: (event: OudsButtonCustomEvent<void>) => void;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'strong' | 'brand' | 'minimal' | 'negative';
        /**
          * @default true
         */
        "wrap"?: boolean;
    }
    interface OudsTextInput {
        "bsPrefix"?: string;
        "bsSuffix"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "label": string;
        /**
          * @default false
         */
        "maxWidth"?: boolean;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        /**
          * @default false
         */
        "outlined"?: boolean;
        /**
          * @default ' '
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "ouds-button": OudsButton;
        "ouds-text-input": OudsTextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ouds-button": LocalJSX.OudsButton & JSXBase.HTMLAttributes<HTMLOudsButtonElement>;
            "ouds-text-input": LocalJSX.OudsTextInput & JSXBase.HTMLAttributes<HTMLOudsTextInputElement>;
        }
    }
}
