'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { OudsButton as OudsButtonElement, defineCustomElement as defineOudsButton } from "@ouds/web-components/dist/components/ouds-button.js";
import { OudsTextInput as OudsTextInputElement, defineCustomElement as defineOudsTextInput } from "@ouds/web-components/dist/components/ouds-text-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type OudsButtonEvents = { onOudsButtonClick: EventName<CustomEvent<void>> };

export const OudsButton: StencilReactComponent<OudsButtonElement, OudsButtonEvents> = /*@__PURE__*/ createComponent<OudsButtonElement, OudsButtonEvents>({
    tagName: 'ouds-button',
    elementClass: OudsButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onOudsButtonClick: 'oudsButtonClick' } as OudsButtonEvents,
    defineCustomElement: defineOudsButton
});

export type OudsTextInputEvents = NonNullable<unknown>;

export const OudsTextInput: StencilReactComponent<OudsTextInputElement, OudsTextInputEvents> = /*@__PURE__*/ createComponent<OudsTextInputElement, OudsTextInputEvents>({
    tagName: 'ouds-text-input',
    elementClass: OudsTextInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as OudsTextInputEvents,
    defineCustomElement: defineOudsTextInput
});
