/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Boostrap Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 * @see site/src/libs/astro.ts
 */
export declare global {
  export const AddedIn: typeof import('@shortcodes/AddedIn.astro').default
  export const BsTable: typeof import('@shortcodes/BsTable.astro').default
  export const Callout: typeof import('@shortcodes/Callout.astro').default
  export const CalloutDeprecatedDarkVariables: typeof import('@shortcodes/CalloutDeprecatedDarkVariables.astro').default
  export const Code: typeof import('@shortcodes/Code.astro').default
  export const DesignCalloutAlert: typeof import('@shortcodes/DesignCalloutAlert.astro').default
}
