/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Boostrap Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 * @see site/src/libs/astro.ts
 */
export declare global {
  export const AddedIn: typeof import('@shortcodes/AddedIn.astro').default
  export const BsTable: typeof import('@shortcodes/BsTable.astro').default
  export const Callout: typeof import('@shortcodes/Callout.astro').default
  export const CalloutDeprecatedDarkVariants: typeof import('@shortcodes/CalloutDeprecatedDarkVariants.astro').default
  export const Card: typeof import('@shortcodes/Card.astro').default
  export const Code: typeof import('@shortcodes/Code.astro').default
  export const DeprecatedIn: typeof import('@shortcodes/DeprecatedIn.astro').default
  export const DesignCalloutAlert: typeof import('@shortcodes/DesignCalloutAlert.astro').default
  export const EnableBtnCloseTooltip: typeof import('@shortcodes/EnableBtnCloseTooltip.astro').default
  export const Example: typeof import('@shortcodes/Example.astro').default
  export const JsDismiss: typeof import('@shortcodes/JsDismiss.astro').default
  export const JsDocs: typeof import('@shortcodes/JsDocs.astro').default
  export const OrangeFooter: typeof import('@shortcodes/OrangeFooter.astro').default
  export const OrangeGlobalHeaders: typeof import('@shortcodes/OrangeGlobalHeaders.astro').default
  export const OrangeSupra: typeof import('@shortcodes/OrangeSupra.astro').default
  export const Placeholder: typeof import('@shortcodes/Placeholder.astro').default
  export const ScssDocs: typeof import('@shortcodes/ScssDocs.astro').default
  export const SvgDocs: typeof import('@shortcodes/SvgDocs.astro').default
  export const Table: typeof import('@shortcodes/Table.astro').default
}
