name: CSS
on:
  push:
    branches:
      - main
    paths:
      - "scss/**"
      - "packages/**/scss/**"
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 24

permissions:
  contents: read

jobs:
  css:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Build CSS
        run: npm run css

      - name: Run CSS tests
        run: npm run css-test

      - name: Run CSS snapshot tests
        run: npm run css-snapshot-test

      # Check that there are no stylelint multiline comments (e.g. /* stylelint-disable */)
      - name: Check built CSS files
        shell: bash
        run: |
          if [[ $(find packages/orange/dist/css/ -name "*.css" | xargs grep -F "/* stylelint" | wc -l | bc) -eq 0 ]]; then
            echo "All good, no stylelint multiline comments found"
            exit 0
          else
            echo "Found stylelint multiline comments!"
            exit 1
          fi
